import type { Addiction } from "./addictions";

/** Fichas técnicas únicas para adicciones top — sobreescriben los textos genéricos. */
export const OVERRIDES: Record<string, Partial<Pick<Addiction, "info" | "causes" | "symptoms" | "solutions">>> = {
  alcohol: {
    info: "Trastorno por uso de alcohol: dependencia física y psicológica al etanol, depresor del sistema nervioso central que altera juicio, memoria e hígado.",
    causes: [
      "Normalización cultural del consumo en fiestas y reuniones",
      "Historia familiar de alcoholismo (componente genético)",
      "Auto-medicación de ansiedad social o duelo",
      "Baja tolerancia al malestar emocional",
    ],
    symptoms: [
      "Temblores matutinos y sudoración al no beber",
      "Lagunas mentales (blackouts) tras consumo",
      "Tolerancia: cada vez se necesita más para emborracharse",
      "Mentiras sobre cuánto se bebe realmente",
    ],
    solutions: [
      "Desintoxicación supervisada (riesgo de delirium tremens)",
      "Grupos de 12 pasos (AA) o SMART Recovery",
      "Identificar los detonantes sociales: viernes, estrés laboral",
      "Plan B para reuniones: bebidas sin alcohol preparadas",
    ],
  },
  tabaco: {
    info: "Dependencia a la nicotina. El cigarrillo entrega nicotina al cerebro en 7 segundos, creando uno de los circuitos de recompensa más rápidos que existen.",
    causes: [
      "Inicio en adolescencia por presión de grupo",
      "Asociación cigarrillo-café, cigarrillo-conducción",
      "Manejo de ansiedad y pausas en el trabajo",
      "Imitación de figuras familiares fumadoras",
    ],
    symptoms: [
      "Tos crónica matutina y flemas",
      "Irritabilidad extrema en las primeras 72 horas sin nicotina",
      "Ansiedad oral: ganas de tener algo en la boca",
      "Manchas amarillas en dedos y dientes",
    ],
    solutions: [
      "Terapia de reemplazo (parches, chicles, sprays)",
      "Identificar el 'cigarrillo gatillo' del día y romperlo primero",
      "Ejercicio aeróbico: reduce el craving en 5 minutos",
      "Recompensar con el dinero ahorrado semana a semana",
    ],
  },
  vapeo: {
    info: "Dependencia a cigarrillos electrónicos. Una sola cápsula puede equivaler a 20 cigarrillos en nicotina, con sabores que enmascaran el daño pulmonar (EVALI).",
    causes: [
      "Marketing dirigido a jóvenes con sabores frutales",
      "Falsa percepción de 'es solo vapor inofensivo'",
      "Sustitución del cigarrillo tradicional sin dejar la nicotina",
      "Diseño portátil que permite uso constante todo el día",
    ],
    symptoms: [
      "Vapeo en cama, en el baño, durante reuniones",
      "Tos seca y sensación de quemazón en garganta",
      "Ansiedad si la batería se descarga",
      "Aumento del ritmo cardíaco en reposo",
    ],
    solutions: [
      "Bajar gradualmente la concentración de nicotina (mg/ml)",
      "Reemplazar la gestualidad oral con chicle sin azúcar",
      "Eliminar el dispositivo de los lugares de trabajo y dormitorio",
      "Reportar síntomas pulmonares a un neumólogo",
    ],
  },
  videojuegos: {
    info: "Trastorno por uso de videojuegos (CIE-11). El cerebro recibe dopamina por logros virtuales y desplaza recompensas reales como estudio, sueño y socialización.",
    causes: [
      "Escape de la realidad por bullying, estrés o aburrimiento",
      "Diseño persuasivo: loot boxes, eventos limitados, ranking",
      "Identidad construida dentro del juego (clan, gremio)",
      "Falta de hobbies offline alternativos",
    ],
    symptoms: [
      "Jugar 6+ horas seguidas sin notar el tiempo",
      "Insomnio por sesiones nocturnas",
      "Irritabilidad cuando se interrumpe la partida",
      "Bajón académico o laboral notable",
    ],
    solutions: [
      "Límites duros: temporizador del router o app de control",
      "Reemplazar con deportes físicos de equipo",
      "Reuniones presenciales con la comunidad del juego (mover offline)",
      "Eliminar microtransacciones de la tarjeta",
    ],
  },
  redes: {
    info: "Uso problemático de redes sociales. Cada notificación libera dopamina por anticipación, generando el mismo circuito que las máquinas tragamonedas.",
    causes: [
      "Algoritmos diseñados para maximizar tiempo en pantalla",
      "Comparación constante con vidas filtradas de otros",
      "Necesidad de validación vía likes y comentarios",
      "FOMO: miedo a perderse lo que pasa en el grupo",
    ],
    symptoms: [
      "Revisar el teléfono apenas abrir los ojos",
      "Phantom vibration: sentir notificaciones que no existen",
      "Ansiedad si una publicación tiene pocos likes",
      "Scroll inconsciente durante conversaciones reales",
    ],
    solutions: [
      "Quitar las apps del dock principal, esconderlas en carpetas",
      "Modo escala de grises: reduce la atracción visual",
      "Dejar el teléfono fuera del dormitorio",
      "Sustituir los 5 primeros minutos del día por respiración",
    ],
  },
  pornografia: {
    info: "Uso compulsivo de contenido sexual digital. Sobrestimula el sistema dopaminérgico al ofrecer novedad infinita, generando tolerancia y disfunciones sexuales reales.",
    causes: [
      "Acceso gratuito ilimitado desde la pubertad",
      "Refugio ante soledad o rechazo afectivo",
      "Curiosidad escalada a contenido más extremo",
      "Privacidad total: nadie ve lo que consumes",
    ],
    symptoms: [
      "Disfunción eréctil con pareja real",
      "Pérdida de interés en relaciones afectivas",
      "Vergüenza y aislamiento post-uso",
      "Necesidad de contenido cada vez más fuerte",
    ],
    solutions: [
      "Filtros de contenido + responsable de rendición de cuentas",
      "Reboot: período de abstinencia (NoFap) de 60-90 días",
      "Terapia sexual y reconexión con intimidad real",
      "Identificar los desencadenantes emocionales reales",
    ],
  },
  apuestas: {
    info: "Ludopatía o trastorno de juego patológico. El cerebro responde más a la posibilidad de ganar que a la ganancia misma — el 'casi-ganar' es la trampa principal.",
    causes: [
      "Refuerzo intermitente (la recompensa más adictiva conocida)",
      "Ilusión de control sobre el azar",
      "Necesidad de recuperar pérdidas (efecto chasing)",
      "Disponibilidad 24/7 en apps móviles",
    ],
    symptoms: [
      "Apostar más dinero del planeado",
      "Mentir a la familia sobre pérdidas",
      "Pedir prestado para seguir jugando",
      "Sensación de vacío fuera del juego",
    ],
    solutions: [
      "Autoexclusión voluntaria en plataformas y casinos",
      "Control total del dinero por un tercero de confianza",
      "Grupo de Jugadores Anónimos",
      "Bloqueadores de apps de apuestas en el celular",
    ],
  },
  cafeina: {
    info: "Dependencia a la cafeína. Bloquea los receptores de adenosina y aumenta dopamina y cortisol; al suspender, aparece migraña por vasodilatación rebote.",
    causes: [
      "Cultura del rendimiento y multitarea",
      "Compensar mala calidad de sueño",
      "Ritual social: café con colegas",
      "Disponibilidad masiva de energéticas",
    ],
    symptoms: [
      "Migraña intensa al saltarse el café diario",
      "Taquicardia y temblor fino en manos",
      "Ansiedad y dificultad para dormir",
      "Necesidad de aumentar la dosis cada mes",
    ],
    solutions: [
      "Reducir 25% por semana en lugar de cortar de golpe",
      "Hidratación abundante: muchos síntomas son por sed",
      "Té verde como puente: menos cafeína, más L-teanina",
      "Higiene del sueño: dormir bien elimina la necesidad",
    ],
  },
  compras: {
    info: "Oniomanía o compra compulsiva. El acto de comprar libera dopamina; la culpa post-compra alimenta el ciclo y suele acompañar a depresión.",
    causes: [
      "Regulación emocional vía consumo ('retail therapy')",
      "Publicidad personalizada y 1-click checkout",
      "Identidad vinculada a marcas y estatus",
      "Soledad y necesidad de novedad",
    ],
    symptoms: [
      "Compras con tarjeta sin recordar haberlas hecho",
      "Paquetes sin abrir acumulándose en casa",
      "Deuda creciente y mentiras a la pareja",
      "Euforia breve seguida de culpa intensa",
    ],
    solutions: [
      "Regla de 72 horas antes de comprar lo no esencial",
      "Eliminar tarjetas guardadas en navegadores y apps",
      "Cancelar suscripciones de email promocional",
      "Hobby creativo que produzca, no que consuma",
    ],
  },
  cocaina: {
    info: "Trastorno por uso de cocaína. Estimulante que multiplica la dopamina sináptica al bloquear su recaptación; el bajón posterior empuja a re-dosificar.",
    causes: [
      "Búsqueda de euforia en entornos de fiesta y riesgo",
      "Industria laboral con jornadas extremas (finanzas, hospitality)",
      "Cultura aspiracional asociada a estatus y poder",
      "Co-uso con alcohol que reduce la percepción de daño",
    ],
    symptoms: [
      "Dilatación pupilar marcada y congestión nasal crónica",
      "Insomnio de varios días seguidos con energía artificial",
      "Paranoia, irritabilidad y agresividad post-consumo",
      "Dolor torácico y arritmias cardíacas",
    ],
    solutions: [
      "Internamiento o hospital de día durante el bajón inicial",
      "Cortar contactos del círculo de consumo (números, lugares)",
      "Manejo médico de comorbilidades cardíacas",
      "Terapia de prevención de recaídas con foco en entornos sociales",
    ],
  },
  cannabis: {
    info: "Trastorno por uso de cannabis. El THC modula los receptores CB1 cerebrales; el uso diario en jóvenes está vinculado a déficit de memoria y trastornos psicóticos.",
    causes: [
      "Percepción social de 'droga blanda inofensiva'",
      "Auto-medicación de insomnio y ansiedad",
      "Ritual social: porro al final del día",
      "Acceso legalizado o decomercializado en aumento",
    ],
    symptoms: [
      "Pérdida de memoria a corto plazo y dificultad de concentración",
      "Apatía sostenida y abandono de proyectos (síndrome amotivacional)",
      "Tos crónica y bronquitis recurrente",
      "Crisis de ansiedad o paranoia con cepas altas en THC",
    ],
    solutions: [
      "Eliminar parafernalia (pipas, papel) de la vista",
      "Sustituir el ritual nocturno por té relajante o ejercicio suave",
      "Pedir analítica médica a los 30 días para mostrar mejoría",
      "Terapia cognitivo-conductual breve enfocada en cannabis",
    ],
  },
  heroina: {
    info: "Dependencia a opiáceos ilegales. La heroína atraviesa la barrera hematoencefálica en segundos, generando una de las dependencias físicas más severas conocidas.",
    causes: [
      "Escalada desde analgésicos opioides recetados",
      "Trauma severo no tratado (combate, abuso)",
      "Entornos de marginación y exclusión social",
      "Anestesia química frente al dolor emocional",
    ],
    symptoms: [
      "Calambres musculares intensos y dolor óseo",
      "Náuseas, vómitos y diarrea explosiva al retirar",
      "Sudoración profusa, piloerección (piel de gallina)",
      "Rinorrea, lagrimeo y bostezos compulsivos",
    ],
    solutions: [
      "Tratamiento sustitutivo con metadona o buprenorfina",
      "Naloxona disponible en casa por riesgo de sobredosis",
      "Programa de reducción de daños con jeringas estériles",
      "Vivienda y empleo asistido durante los primeros 6 meses",
    ],
  },
  comida: {
    info: "Trastorno por atracón. Episodios de ingesta rápida y descontrolada de grandes cantidades, sin conducta compensatoria, acompañados de vergüenza intensa.",
    causes: [
      "Restricción dietética extrema que dispara rebote",
      "Regulación emocional mediante azúcar y grasas (comfort food)",
      "Historia de dietas yo-yo desde la infancia",
      "Imagen corporal distorsionada y baja autoestima",
    ],
    symptoms: [
      "Comer hasta sentir malestar físico doloroso",
      "Esconder envoltorios y comer a escondidas",
      "Atracones nocturnos en soledad",
      "Culpa y disforia post-atracón que dura horas",
    ],
    solutions: [
      "Comer 5 veces al día con horarios fijos (no restringir)",
      "Identificar emoción detonante antes de abrir el refrigerador",
      "Terapia con nutricionista no-dietista + psicólogo",
      "Eliminar balanzas y espejos provocadores durante 90 días",
    ],
  },
  trabajo: {
    info: "Workaholism. Adicción al trabajo donde la productividad y el rendimiento se vuelven el único marcador de autovaloración, desplazando salud y vínculos.",
    causes: [
      "Identidad construida sobre logros profesionales",
      "Miedo al vacío y a la introspección",
      "Cultura empresarial que premia el burnout",
      "Validación parental condicionada al éxito",
    ],
    symptoms: [
      "Revisar el correo en vacaciones, comidas y cama",
      "Imposibilidad de desconectar fines de semana",
      "Hipertensión, gastritis y problemas de espalda",
      "Distanciamiento de pareja e hijos sin notarlo",
    ],
    solutions: [
      "Apagado total de notificaciones laborales después de las 7 pm",
      "Agenda obligatoria de ocio no-productivo (sin metas)",
      "Terapia de identidad: '¿quién eres si no trabajas?'",
      "Vacaciones reales mínimo de 10 días seguidos al año",
    ],
  },
  benzodiacepinas: {
    info: "Dependencia a tranquilizantes (clonazepam, alprazolam, diazepam). Potencian el GABA cerebral; al retirarlas el sistema rebota y puede causar convulsiones mortales.",
    causes: [
      "Prescripción prolongada sin reevaluación médica",
      "Auto-medicación para crisis de pánico",
      "Acceso fácil en farmacias de la región",
      "Combinación con alcohol u opiáceos para potenciar efecto",
    ],
    symptoms: [
      "Tolerancia progresiva: la misma dosis ya no calma",
      "Insomnio severo y pesadillas al saltarse una toma",
      "Temblores, sudoración y crisis de pánico de rebote",
      "Riesgo de convulsiones si se corta de golpe",
    ],
    solutions: [
      "Reducción gradual supervisada (10% cada 2 semanas)",
      "Conversión a diazepam de vida media larga para retiro suave",
      "TCC para pánico que reemplace la función química",
      "Nunca suspender abruptamente sin acompañamiento médico",
    ],
  },

  // ─── Sustancias ───
  metanfetamina: {
    info: "Trastorno por uso de metanfetamina. Libera una avalancha de dopamina y daña las terminales nerviosas; la euforia dura horas pero el bajón empuja a consumir sin parar durante días.",
    causes: [
      "Búsqueda de energía y rendimiento extremo (estudio, trabajo, fiestas)",
      "Bajo costo y alta potencia frente a otros estimulantes",
      "Auto-medicación de depresión o fatiga crónica",
      "Entornos donde el consumo está normalizado",
    ],
    symptoms: [
      "Estar despierto 2-3 días seguidos sin dormir ni comer",
      "Rascado compulsivo de la piel y llagas (formicación)",
      "Deterioro dental acelerado ('boca de meth')",
      "Paranoia, alucinaciones y agresividad",
    ],
    solutions: [
      "Tratamiento residencial durante el bajón inicial (riesgo de depresión severa)",
      "Restablecer sueño y nutrición como primera prioridad médica",
      "Terapia de manejo de contingencias (refuerzo por análisis negativos)",
      "Reconstruir rutina diaria estructurada hora por hora",
    ],
  },
  crack: {
    info: "Dependencia al crack, la forma fumable de la cocaína. Llega al cerebro en segundos y el efecto dura pocos minutos, generando un ciclo de consumo compulsivo e intenso.",
    causes: [
      "Efecto inmediato y muy corto que obliga a re-dosificar",
      "Bajo precio por dosis frente a la cocaína en polvo",
      "Contextos de exclusión social y pobreza",
      "Escalada rápida desde el consumo de cocaína esnifada",
    ],
    symptoms: [
      "Episodios de consumo intensivo hasta agotar todo el dinero",
      "Quemaduras en labios y dedos por la pipa",
      "Pérdida de peso brusca y descuido total del aspecto",
      "Irritabilidad, paranoia y conducta de riesgo",
    ],
    solutions: [
      "Apartarse del entorno y los lugares de consumo de inmediato",
      "Internamiento o centro de día durante las primeras semanas",
      "Manejo médico de la ansiedad y el ánimo en la abstinencia",
      "Red de apoyo que controle el acceso al dinero",
    ],
  },
  extasis: {
    info: "Uso problemático de MDMA. Vacía las reservas de serotonina del cerebro para producir euforia y cercanía; los días posteriores aparece un bajón anímico marcado ('martes suicida').",
    causes: [
      "Asociación con música electrónica, fiestas y festivales",
      "Búsqueda de conexión emocional y desinhibición social",
      "Percepción de ser 'seguro' por ser una pastilla",
      "Consumo en grupo como ritual de pertenencia",
    ],
    symptoms: [
      "Bajón depresivo y agotamiento 2-3 días después",
      "Bruxismo (apretar la mandíbula) y deshidratación",
      "Necesidad de subir la dosis para sentir lo mismo",
      "Asociar diversión y fiesta únicamente con la sustancia",
    ],
    solutions: [
      "Separar el ocio nocturno del consumo (planes sin sustancias)",
      "Reponer descanso, hidratación y nutrición tras cada episodio",
      "Información honesta sobre el daño serotoninérgico acumulado",
      "Terapia si se usa para tapar ansiedad social o vacío",
    ],
  },
  lsd: {
    info: "Uso problemático de LSD. Alucinógeno que distorsiona percepción y pensamiento durante horas; no genera dependencia física, pero sí psicológica y riesgo de crisis o flashbacks.",
    causes: [
      "Búsqueda de experiencias místicas o de autoconocimiento",
      "Curiosidad y exploración en entornos contraculturales",
      "Evasión de una realidad sentida como aburrida o dolorosa",
      "Idea de que 'no engancha' y por tanto es inofensivo",
    ],
    symptoms: [
      "'Viajes' cada vez más frecuentes para escapar",
      "Episodios de ansiedad o pánico intensos (mal viaje)",
      "Flashbacks visuales días o semanas después",
      "Desconexión de responsabilidades y relaciones reales",
    ],
    solutions: [
      "Espaciar y frenar el consumo; tratar la psicodependencia",
      "Acompañamiento psicológico, sobre todo si hay antecedentes psicóticos",
      "Resolver el malestar de fondo que se busca evadir",
      "Entorno seguro y apoyo ante crisis o flashbacks",
    ],
  },
  hongos: {
    info: "Uso problemático de hongos psilocibios. Producen alteraciones perceptivas y emocionales intensas; el riesgo principal es psicológico (malos viajes) y la evasión recurrente.",
    causes: [
      "Disponibilidad natural y percepción de ser 'orgánico/seguro'",
      "Búsqueda de introspección o experiencias espirituales",
      "Influencia de tendencias de microdosis en redes",
      "Escape de estados emocionales difíciles",
    ],
    symptoms: [
      "Recurrir a ellos para gestionar emociones o aburrimiento",
      "Episodios de ansiedad, confusión o paranoia durante el efecto",
      "Náuseas y desorientación física",
      "Dependencia psicológica del ritual de consumo",
    ],
    solutions: [
      "Reconocer el patrón de evasión y reducir la frecuencia",
      "Apoyo psicológico para lo que se intenta resolver consumiendo",
      "Evitar consumo en soledad o en estados de ánimo bajos",
      "Sustituir la búsqueda de 'sentido' por prácticas sostenibles (meditación, naturaleza)",
    ],
  },
  ketamina: {
    info: "Uso problemático de ketamina. Anestésico disociativo que separa la mente del cuerpo ('agujero K'); el consumo frecuente daña gravemente la vejiga y la memoria.",
    causes: [
      "Uso recreativo en fiestas por su efecto disociativo",
      "Búsqueda de desconexión emocional y anestesia psíquica",
      "Acceso por su uso médico y veterinario",
      "Auto-medicación de depresión o trauma",
    ],
    symptoms: [
      "Dolor vesical y urinario crónico (cistitis ketamínica)",
      "Lagunas de memoria y confusión persistente",
      "Aislamiento dentro de estados disociativos",
      "Aumento de la dosis para alcanzar el 'agujero K'",
    ],
    solutions: [
      "Evaluación urológica temprana por daño en la vejiga",
      "Tratar el trauma o la depresión subyacente con terapia",
      "Reducir frecuencia y cortar el acceso recreativo",
      "Reconectar con sensaciones corporales reales (ejercicio, contacto)",
    ],
  },
  opioides_rx: {
    info: "Dependencia a opioides recetados (oxicodona, tramadol, codeína). Alivian el dolor pero generan tolerancia rápida; al retirarlos aparece un síndrome de abstinencia muy intenso.",
    causes: [
      "Prescripción prolongada tras cirugía o lesión",
      "Aumento de dosis por cuenta propia al perder efecto",
      "Acceso en farmacias y botiquines familiares",
      "Alivio del dolor emocional además del físico",
    ],
    symptoms: [
      "Tomar más dosis o más seguido de lo recetado",
      "Buscar varias recetas o médicos ('doctor shopping')",
      "Dolores, sudoración y náuseas al saltarse una toma",
      "Estreñimiento crónico y somnolencia",
    ],
    solutions: [
      "Reducción gradual pautada por el médico que recetó",
      "Tratamiento sustitutivo (buprenorfina) si hay dependencia fuerte",
      "Abordar el dolor con fisioterapia y manejo no-opioide",
      "Naloxona en casa ante riesgo de sobredosis",
    ],
  },
  inhalantes: {
    info: "Uso de inhalantes (pegamentos, solventes, aerosoles). Producen una euforia breve inhalando vapores tóxicos que causan daño neuronal grave e incluso muerte súbita.",
    causes: [
      "Bajo costo y fácil acceso a productos domésticos",
      "Inicio a edades muy tempranas",
      "Contextos de calle, abandono o exclusión",
      "Presión de grupo y curiosidad infantil",
    ],
    symptoms: [
      "Olor químico en aliento y ropa",
      "Manchas o irritación alrededor de boca y nariz",
      "Mareos, habla pastosa y torpeza motora",
      "Deterioro cognitivo y de memoria progresivo",
    ],
    solutions: [
      "Atención médica urgente: hay riesgo de muerte súbita",
      "Retirar el acceso a los productos inhalables",
      "Intervención social y familiar, sobre todo en menores",
      "Tratamiento del daño neurológico y rehabilitación cognitiva",
    ],
  },
  ghb: {
    info: "Uso problemático de GHB ('éxtasis líquido'). Depresor del sistema nervioso con un margen muy estrecho entre la dosis recreativa y la sobredosis con pérdida de conciencia.",
    causes: [
      "Uso en fiestas y contextos de chemsex por su desinhibición",
      "Efecto eufórico y sexualizante a dosis bajas",
      "Falsa sensación de control sobre la dosis",
      "Combinación peligrosa con alcohol",
    ],
    symptoms: [
      "Desmayos y pérdidas de conciencia repentinas",
      "Necesidad de re-dosificar cada poco tiempo",
      "Ansiedad, temblores e insomnio severo al dejarlo",
      "Episodios de consumo que terminan en urgencias",
    ],
    solutions: [
      "Retiro supervisado: la abstinencia puede ser grave",
      "Nunca mezclar con alcohol u otros depresores",
      "Apartarse de los entornos de chemsex y consumo",
      "Apoyo psicológico para sexualidad y vínculos sin sustancias",
    ],
  },
  popper: {
    info: "Uso de poppers (nitritos inhalables). Producen una vasodilatación y euforia muy breves; el uso repetido se asocia a conductas de riesgo y daño ocular.",
    causes: [
      "Uso en contextos sexuales y de fiesta",
      "Percepción de ser 'ligero' y legal",
      "Efecto inmediato que invita a repetir",
      "Disponibilidad en tiendas y online",
    ],
    symptoms: [
      "Dolores de cabeza intensos tras el uso",
      "Uso cada vez más frecuente en encuentros",
      "Visión alterada o manchas (toxicidad retiniana)",
      "Asociar el placer sexual solo con la sustancia",
    ],
    solutions: [
      "Revisión oftalmológica si hay alteraciones visuales",
      "Separar la intimidad del uso de poppers",
      "Reducir la frecuencia y los detonantes",
      "Terapia si encubre ansiedad de desempeño sexual",
    ],
  },
  anabolicos: {
    info: "Uso no médico de esteroides anabólicos. Buscan aumentar músculo y rendimiento, pero alteran las hormonas y se acompañan de una imagen corporal distorsionada (vigorexia).",
    causes: [
      "Presión estética por un cuerpo musculado e 'ideal'",
      "Cultura de gimnasio y redes que premian el físico",
      "Búsqueda de resultados rápidos sin paciencia",
      "Baja autoestima ligada a la apariencia",
    ],
    symptoms: [
      "Verse 'pequeño' aunque esté muy musculado",
      "Acné severo, calvicie y cambios de humor (roid rage)",
      "Problemas hormonales y sexuales",
      "Seguir usando pese a los efectos secundarios",
    ],
    solutions: [
      "Evaluación médica hormonal y cardiovascular",
      "Terapia para la imagen corporal y la autoestima",
      "Plan de entrenamiento y nutrición natural realista",
      "Alejarse de comunidades que normalizan el uso",
    ],
  },
  energizantes: {
    info: "Consumo excesivo de bebidas energéticas. Combinan dosis altas de cafeína, azúcar y taurina; su uso constante genera dependencia, ansiedad y problemas cardíacos.",
    causes: [
      "Compensar falta de sueño y exceso de actividad",
      "Marketing ligado a rendimiento, gaming y deporte",
      "Sabor dulce y disponibilidad masiva",
      "Ritual de 'recarga' en estudio o trabajo",
    ],
    symptoms: [
      "Tomar varias latas al día para funcionar",
      "Taquicardia, nerviosismo y mala calidad de sueño",
      "Dolor de cabeza y bajón al no consumir",
      "Ansiedad y dependencia del 'subidón'",
    ],
    solutions: [
      "Reducir gradualmente y cambiar por agua o infusiones",
      "Atacar la raíz: mejorar el sueño y la energía real",
      "Leer etiquetas: la cafeína oculta se acumula",
      "Sustituir el ritual por una pausa activa o un snack saludable",
    ],
  },
  nicotina_bolsa: {
    info: "Dependencia a las bolsas de nicotina orales. Liberan nicotina sin humo ni olor, lo que facilita un consumo continuo y discreto durante todo el día.",
    causes: [
      "Percepción de ser una alternativa 'limpia' al cigarrillo",
      "Uso discreto que pasa desapercibido en cualquier lugar",
      "Sabores que enmascaran la nicotina",
      "Sustituir el tabaco sin abandonar la nicotina",
    ],
    symptoms: [
      "Tener una bolsa puesta casi todo el día",
      "Irritación de encías y boca",
      "Irritabilidad y ansiedad sin nicotina",
      "Aumentar la concentración para sentir efecto",
    ],
    solutions: [
      "Bajar la concentración de nicotina por etapas",
      "Sustituir la gestualidad oral por chicle sin azúcar",
      "Identificar y romper los momentos gatillo del día",
      "Calcular el ahorro y celebrarlo semanalmente",
    ],
  },
  chimo: {
    info: "Dependencia al chimó o tabaco mascado. Pasta de tabaco que se mantiene en la boca; aporta nicotina y conlleva alto riesgo de lesiones y cáncer bucal.",
    causes: [
      "Tradición y arraigo cultural en algunas regiones",
      "Uso permitido donde no se puede fumar",
      "Inicio temprano por imitación familiar",
      "Manejo de la ansiedad y la concentración",
    ],
    symptoms: [
      "Necesidad de tenerlo en la boca para estar tranquilo",
      "Manchas y retracción de encías; lesiones bucales",
      "Mal aliento y alteración del gusto",
      "Irritabilidad al intentar dejarlo",
    ],
    solutions: [
      "Revisión odontológica para detectar lesiones a tiempo",
      "Reducción progresiva con apoyo para la nicotina",
      "Sustituir el hábito oral por alternativas sanas",
      "Acompañamiento para manejar la ansiedad sin tabaco",
    ],
  },
  kratom: {
    info: "Uso problemático de kratom. Planta con efectos estimulantes a dosis bajas y opioides a dosis altas; el uso diario genera tolerancia y un síndrome de abstinencia real.",
    causes: [
      "Auto-medicación de dolor, ansiedad o fatiga",
      "Intento de dejar opioides sin ayuda profesional",
      "Venta como suplemento 'natural y legal'",
      "Acceso fácil online y en tiendas",
    ],
    symptoms: [
      "Aumentar la dosis para mantener el efecto",
      "Náuseas, sudoración e irritabilidad al dejarlo",
      "Dolores musculares y ansiedad de rebote",
      "Consumir varias veces al día para 'estar bien'",
    ],
    solutions: [
      "Reducción gradual en lugar de corte brusco",
      "Tratar el dolor o la ansiedad con apoyo médico",
      "Acompañamiento si se usaba para salir de opioides",
      "Hidratación y manejo de síntomas en la abstinencia",
    ],
  },
  salvia: {
    info: "Uso problemático de Salvia divinorum. Alucinógeno muy potente y de efecto breve pero intenso; el riesgo principal es psicológico, con experiencias desorientadoras.",
    causes: [
      "Curiosidad por su potencia y duración corta",
      "Disponibilidad legal en algunos lugares",
      "Difusión de videos de consumo en redes",
      "Búsqueda de experiencias extremas",
    ],
    symptoms: [
      "Episodios intensos de desorientación y miedo",
      "Pérdida momentánea de noción de identidad",
      "Repetir el consumo pese a malas experiencias",
      "Conductas de riesgo durante el efecto",
    ],
    solutions: [
      "Frenar el consumo y entender el riesgo psicológico",
      "Nunca usar a solas o en lugares peligrosos",
      "Apoyo psicológico ante crisis de ansiedad",
      "Canalizar la búsqueda de intensidad en actividades seguras",
    ],
  },
  crystal: {
    info: "Dependencia al crystal (metanfetamina cristalizada fumada). Su efecto es muy duradero y se asocia al chemsex; deteriora rápidamente la salud física, mental y sexual.",
    causes: [
      "Uso en sesiones prolongadas de chemsex",
      "Desinhibición y aumento del deseo sexual",
      "Aislamiento, soledad o rechazo afectivo",
      "Entornos donde el consumo está normalizado",
    ],
    symptoms: [
      "Sesiones de varios días sin dormir ni comer",
      "Conductas sexuales de riesgo bajo los efectos",
      "Paranoia, alucinaciones y deterioro dental",
      "Imposibilidad de disfrutar el sexo sin la sustancia",
    ],
    solutions: [
      "Tratamiento especializado en adicción y chemsex",
      "Restablecer sueño y nutrición como urgencia médica",
      "Reconstruir intimidad y placer sin sustancias en terapia",
      "Red de apoyo y alejamiento de los entornos de consumo",
    ],
  },

  // ─── Conductuales ───
  apuestas_online: {
    info: "Apuestas deportivas y casino online. La accesibilidad 24/7 desde el móvil y los bonos de bienvenida convierten cualquier momento en una oportunidad de apostar.",
    causes: [
      "Disponibilidad permanente en una app en el bolsillo",
      "Bonos, cuotas y notificaciones diseñados para enganchar",
      "Ilusión de 'saber de deporte' y controlar el resultado",
      "Apostar para recuperar lo perdido (efecto chasing)",
    ],
    symptoms: [
      "Apostar durante el trabajo, clases o reuniones",
      "Depositar más dinero del planeado una y otra vez",
      "Revisar resultados constantemente con ansiedad",
      "Ocultar pérdidas y saldos a la familia",
    ],
    solutions: [
      "Autoexclusión en las plataformas y apps de apuestas",
      "Bloqueadores de apps y de pagos en el celular",
      "Delegar el control del dinero en alguien de confianza",
      "Grupo de Jugadores Anónimos o terapia especializada",
    ],
  },
  cripto_trading: {
    info: "Trading compulsivo de cripto y mercados. La volatilidad 24/7 y la posibilidad de grandes ganancias activan el mismo circuito de recompensa que el juego de azar.",
    causes: [
      "Mercados abiertos día y noche sin pausa",
      "Promesa de hacerse rico rápido y sin esfuerzo",
      "Comunidades y 'gurús' que alimentan la euforia (FOMO)",
      "Necesidad de recuperar pérdidas con más operaciones",
    ],
    symptoms: [
      "Revisar gráficos compulsivamente, incluso de madrugada",
      "Operar por impulso y emoción, no por estrategia",
      "Invertir dinero que se necesita para vivir",
      "Cambios de humor atados al valor de la cartera",
    ],
    solutions: [
      "Reglas escritas de inversión y límites de pérdida",
      "Eliminar apps de trading del móvil y las alertas de precio",
      "Invertir solo lo que se puede perder, de forma automática",
      "Tratar el componente de juego con apoyo psicológico",
    ],
  },
  ejercicio: {
    info: "Ejercicio compulsivo o vigorexia conductual. La actividad física, sana en su justa medida, se vuelve una obligación rígida que ignora el descanso y las lesiones.",
    causes: [
      "Imagen corporal y miedo a 'perder la forma'",
      "Uso del ejercicio para regular ansiedad y culpa",
      "Cultura del 'no pain, no gain' y comparación en redes",
      "Sensación de control sobre el cuerpo y la vida",
    ],
    symptoms: [
      "Entrenar lesionado o enfermo sin permitirse parar",
      "Culpa intensa al saltarse un entrenamiento",
      "Sacrificar trabajo, vínculos o sueño por entrenar",
      "Lesiones recurrentes por sobreentrenamiento",
    ],
    solutions: [
      "Plan con días de descanso obligatorios y no negociables",
      "Trabajar la imagen corporal y la autoexigencia en terapia",
      "Variar el movimiento por placer, no por castigo",
      "Escuchar las señales de dolor y fatiga del cuerpo",
    ],
  },
  sexo: {
    info: "Conducta sexual compulsiva. Búsqueda repetida de sexo o excitación para regular emociones, que se mantiene pese a las consecuencias y a la pérdida de control.",
    causes: [
      "Regulación de ansiedad, vacío o baja autoestima",
      "Historia de trauma o apego inseguro",
      "Acceso ilimitado a contactos y contenido",
      "Búsqueda constante de novedad y validación",
    ],
    symptoms: [
      "Dedicar mucho tiempo a buscar encuentros o contenido",
      "Conductas de riesgo pese a posibles consecuencias",
      "Sensación de culpa y vacío después",
      "Intentos fallidos de reducir la conducta",
    ],
    solutions: [
      "Terapia especializada en conducta sexual compulsiva",
      "Identificar las emociones que disparan la búsqueda",
      "Reconstruir intimidad basada en vínculo, no en cantidad",
      "Grupos de apoyo y rendición de cuentas",
    ],
  },
  masturbacion: {
    info: "Masturbación compulsiva. Práctica normal que se vuelve problemática cuando es la principal vía de escape y empieza a interferir con la vida diaria y la intimidad.",
    causes: [
      "Vía rápida para aliviar estrés, aburrimiento o insomnio",
      "Asociación fuerte con consumo de pornografía",
      "Evitación de la intimidad real o del rechazo",
      "Ritual automático en momentos de soledad",
    ],
    symptoms: [
      "Hacerlo varias veces al día de forma automática",
      "Interferir con trabajo, sueño o relaciones",
      "Culpa y malestar después, sin poder reducirlo",
      "Pérdida de interés en la intimidad con la pareja",
    ],
    solutions: [
      "Identificar y cambiar los momentos gatillo (soledad, aburrimiento)",
      "Reducir el acceso a la pornografía asociada",
      "Llenar el tiempo con actividad física o social",
      "Terapia si encubre ansiedad, trauma o aislamiento",
    ],
  },
  relaciones: {
    info: "Codependencia afectiva. Necesidad enfermiza de la aprobación o presencia de otra persona, hasta el punto de anular las propias necesidades e identidad.",
    causes: [
      "Apego inseguro y miedo intenso al abandono",
      "Baja autoestima que busca valor en la pareja",
      "Modelos familiares de relaciones dependientes",
      "Idealización del amor romántico como salvación",
    ],
    symptoms: [
      "Pánico ante la posibilidad de quedarse solo/a",
      "Anular gustos, planes y amistades por la pareja",
      "Aguantar relaciones dañinas con tal de no romper",
      "Necesitar confirmación constante de ser querido/a",
    ],
    solutions: [
      "Reconstruir identidad y proyectos propios fuera de la pareja",
      "Terapia para trabajar apego y autoestima",
      "Recuperar amistades y red de apoyo independiente",
      "Aprender a tolerar la soledad sin sentirla como amenaza",
    ],
  },
  mentira: {
    info: "Mitomanía o mentira compulsiva. Necesidad de mentir incluso sin beneficio claro; la mentira regula la autoimagen y la ansiedad, pero erosiona toda confianza.",
    causes: [
      "Baja autoestima y necesidad de impresionar",
      "Evitar el conflicto o las consecuencias",
      "Aprendizaje temprano de la mentira como defensa",
      "Construir una imagen idealizada de uno mismo",
    ],
    symptoms: [
      "Mentir de forma automática, incluso en cosas triviales",
      "Inventar historias cada vez más elaboradas",
      "Contradicciones que dañan relaciones y trabajo",
      "Dificultad para parar aun queriendo",
    ],
    solutions: [
      "Terapia para la autoestima y la necesidad de aprobación",
      "Practicar la honestidad en situaciones pequeñas y seguras",
      "Detectar el impulso antes de mentir y hacer una pausa",
      "Reparar la confianza con transparencia sostenida",
    ],
  },
  robar: {
    info: "Cleptomanía. Impulso irresistible de robar objetos que no se necesitan; la tensión previa y el alivio posterior son el centro del problema, no el valor de lo robado.",
    causes: [
      "Acumulación de tensión que solo se alivia robando",
      "Trastornos del control de impulsos asociados",
      "Ansiedad, depresión o vacío emocional de fondo",
      "Refuerzo por la descarga de adrenalina del acto",
    ],
    symptoms: [
      "Tensión creciente antes de robar",
      "Alivio o euforia momentánea durante el acto",
      "Culpa y vergüenza intensas después",
      "Robar objetos inútiles, que luego se guardan o tiran",
    ],
    solutions: [
      "Terapia cognitivo-conductual del control de impulsos",
      "Identificar y manejar la tensión con otras vías",
      "Tratar la ansiedad o depresión subyacente",
      "Estrategias para evitar situaciones de riesgo",
    ],
  },
  piromania: {
    info: "Piromanía. Fascinación e impulso compulsivo de provocar fuego por la tensión y el alivio que genera, no por beneficio o venganza.",
    causes: [
      "Atracción intensa por el fuego desde la infancia",
      "Tensión interna que se descarga con el acto",
      "Dificultades de control de impulsos",
      "Necesidad de estimulación y sensación de poder",
    ],
    symptoms: [
      "Fascinación persistente con fuego y su parafernalia",
      "Tensión previa y alivio al provocarlo o verlo",
      "Provocar fuegos pese al peligro evidente",
      "Falta de remordimiento proporcional al riesgo",
    ],
    solutions: [
      "Atención profesional urgente por el alto riesgo",
      "Terapia del control de impulsos y manejo de la tensión",
      "Supervisión y eliminación del acceso a material inflamable",
      "Tratar trastornos asociados (ansiedad, impulsividad)",
    ],
  },
  tricotilomania: {
    info: "Tricotilomanía. Necesidad recurrente de arrancarse el pelo (cabeza, cejas, pestañas), que alivia tensión pero deja zonas sin cabello y mucha vergüenza.",
    causes: [
      "Regulación de ansiedad, estrés o aburrimiento",
      "Conducta repetitiva centrada en el cuerpo",
      "Estados de concentración o distracción (ver TV, leer)",
      "Componente de tensión-alivio automático",
    ],
    symptoms: [
      "Zonas con menos pelo o calvas por el arrancado",
      "Tensión antes y alivio durante el acto",
      "Hacerlo de forma automática sin darse cuenta",
      "Evitar peluquerías, piscinas o fotos por vergüenza",
    ],
    solutions: [
      "Entrenamiento de reversión de hábitos (HRT) con terapeuta",
      "Identificar los disparadores y ocupar las manos",
      "Barreras suaves (guantes, gorro) en momentos de riesgo",
      "Tratar la ansiedad de base sin culpabilizarse",
    ],
  },
  dermatilomania: {
    info: "Dermatilomanía. Rascarse o pellizcarse la piel de forma compulsiva hasta dañarla, en un ciclo de tensión y alivio difícil de frenar.",
    causes: [
      "Regulación de ansiedad y estrés",
      "Búsqueda de 'corregir' imperfecciones de la piel",
      "Conducta automática en momentos de distracción",
      "Perfeccionismo aplicado al propio cuerpo",
    ],
    symptoms: [
      "Heridas, costras y marcas por el pellizcado",
      "Pasar mucho tiempo frente al espejo buscando 'defectos'",
      "Alivio momentáneo seguido de culpa",
      "Tapar las lesiones con ropa o maquillaje",
    ],
    solutions: [
      "Entrenamiento de reversión de hábitos con apoyo profesional",
      "Mantener las manos ocupadas y la piel hidratada/cubierta",
      "Reducir espejos y luces que invitan a inspeccionarse",
      "Tratar la ansiedad y el perfeccionismo de fondo",
    ],
  },
  onicofagia: {
    info: "Onicofagia. Comerse las uñas de forma crónica, normalmente ligada a la ansiedad; daña uñas y dedos y resiste a los intentos de dejarlo por voluntad.",
    causes: [
      "Descarga de ansiedad, estrés o aburrimiento",
      "Hábito automático arraigado desde la infancia",
      "Concentración o nerviosismo (exámenes, esperas)",
      "Imitación de modelos familiares",
    ],
    symptoms: [
      "Uñas muy cortas, dañadas y dedos lastimados",
      "Morderse sin darse cuenta en momentos de tensión",
      "Vergüenza por el aspecto de las manos",
      "Infecciones o problemas dentales leves",
    ],
    solutions: [
      "Identificar los momentos gatillo y ocupar las manos",
      "Esmalte de sabor amargo como barrera",
      "Técnicas de manejo de ansiedad (respiración, pausas)",
      "Sustituir por un objeto antiestrés para las manos",
    ],
  },
  procrastinacion: {
    info: "Procrastinación crónica. Postergar de forma compulsiva tareas importantes buscando alivio inmediato, lo que aumenta la culpa y la ansiedad a largo plazo.",
    causes: [
      "Evitar la incomodidad o el miedo al fracaso",
      "Tareas percibidas como abrumadoras o aburridas",
      "Búsqueda de recompensa inmediata (móvil, series)",
      "Perfeccionismo que paraliza el inicio",
    ],
    symptoms: [
      "Dejar todo para el último momento de forma habitual",
      "Llenar el tiempo con distracciones 'productivas'",
      "Culpa y estrés crecientes por lo pendiente",
      "Sensación de bloqueo ante tareas importantes",
    ],
    solutions: [
      "Dividir las tareas en pasos pequeños de 5-10 minutos",
      "Técnica Pomodoro y eliminar distracciones del entorno",
      "Empezar por lo mínimo viable, sin buscar perfección",
      "Trabajar el miedo al fracaso y la autoexigencia",
    ],
  },
  perfeccionismo: {
    info: "Perfeccionismo tóxico. Exigencia desmedida que nunca se siente satisfecha; en lugar de mejorar el resultado, paraliza, agota y daña la autoestima.",
    causes: [
      "Autoestima condicionada a logros y aprobación",
      "Miedo intenso al error y al juicio ajeno",
      "Modelos de crianza muy exigentes",
      "Confundir valía personal con rendimiento",
    ],
    symptoms: [
      "No terminar o no entregar por no estar 'perfecto'",
      "Autocrítica feroz ante cualquier fallo",
      "Procrastinación por miedo a no hacerlo bien",
      "Agotamiento y ansiedad constantes",
    ],
    solutions: [
      "Practicar el 'suficientemente bueno' a propósito",
      "Separar la valía personal del resultado",
      "Exponerse a errores controlados para tolerarlos",
      "Terapia cognitiva para los estándares rígidos",
    ],
  },
  control: {
    info: "Control obsesivo. Necesidad de controlar personas, planes y detalles para calmar la ansiedad; el alivio es breve y deteriora los vínculos y la propia paz.",
    causes: [
      "Ansiedad e intolerancia a la incertidumbre",
      "Experiencias pasadas de caos o falta de seguridad",
      "Creencia de que 'si no controlo, todo sale mal'",
      "Baja confianza en los demás",
    ],
    symptoms: [
      "Microgestionar a otros y no poder delegar",
      "Ansiedad intensa ante imprevistos o cambios",
      "Conflictos por imponer la propia forma de hacer",
      "Agotamiento por querer abarcarlo todo",
    ],
    solutions: [
      "Practicar tolerar la incertidumbre en cosas pequeñas",
      "Delegar de forma progresiva y soltar el resultado",
      "Técnicas de manejo de ansiedad",
      "Terapia para la necesidad de control y la confianza",
    ],
  },
  acumulacion: {
    info: "Trastorno de acumulación. Dificultad persistente para desprenderse de objetos, hasta llenar y bloquear los espacios; tirar algo genera una angustia intensa.",
    causes: [
      "Apego emocional o 'utilidad futura' atribuida a los objetos",
      "Miedo a necesitarlo después o a perder recuerdos",
      "Ansiedad y dificultad en la toma de decisiones",
      "Duelo o vacío que se llena con cosas",
    ],
    symptoms: [
      "Espacios inutilizados por la cantidad de objetos",
      "Angustia intensa al intentar desechar algo",
      "Compras o recolección continua de cosas",
      "Aislamiento por vergüenza del estado del hogar",
    ],
    solutions: [
      "Terapia cognitivo-conductual específica de acumulación",
      "Descartar por zonas pequeñas y con acompañamiento",
      "Reglas claras de qué entra y qué sale",
      "Tratar la ansiedad y el duelo de base",
    ],
  },
  limpieza: {
    info: "Limpieza compulsiva. Rituales de higiene y orden excesivos para calmar la ansiedad o el miedo a la contaminación, que consumen tiempo y desgastan a la persona.",
    causes: [
      "Ansiedad y miedo a la suciedad o los gérmenes",
      "Necesidad de control y orden para sentirse seguro",
      "Rasgos obsesivo-compulsivos",
      "Búsqueda de alivio a través del ritual",
    ],
    symptoms: [
      "Limpiar durante horas aunque ya esté limpio",
      "Ansiedad intensa si algo está 'fuera de lugar'",
      "Lavado de manos repetido hasta dañar la piel",
      "Conflictos por imponer los rituales a los demás",
    ],
    solutions: [
      "Exposición gradual a la 'imperfección' sin limpiar",
      "Terapia cognitivo-conductual para rituales (TOC)",
      "Limitar el tiempo de limpieza con horarios",
      "Tratar la ansiedad subyacente",
    ],
  },
  conducir: {
    info: "Conducción temeraria compulsiva. Búsqueda de adrenalina al volante (velocidad, riesgo) que pone en peligro la propia vida y la de otros.",
    causes: [
      "Búsqueda de adrenalina y emociones fuertes",
      "Impulsividad y baja percepción del riesgo",
      "Necesidad de descargar ira o estrés",
      "Refuerzo social o competencia con otros",
    ],
    symptoms: [
      "Exceder velocidad y maniobras de riesgo de forma habitual",
      "Sensación de euforia al conducir al límite",
      "Multas o incidentes recurrentes",
      "Irritabilidad y agresividad al volante",
    ],
    solutions: [
      "Canalizar la adrenalina en deportes seguros y regulados",
      "Trabajar la impulsividad y la gestión de la ira",
      "Conciencia real del riesgo (datos, testimonios)",
      "Terapia si encubre necesidad de riesgo o autodestrucción",
    ],
  },
  riesgo: {
    info: "Búsqueda compulsiva de riesgo extremo. Necesidad constante de adrenalina mediante conductas peligrosas para sentirse vivo; sin ellas aparece vacío o aburrimiento.",
    causes: [
      "Baja respuesta del sistema de recompensa a lo cotidiano",
      "Necesidad de sentir intensidad para 'estar vivo'",
      "Impulsividad y tolerancia alta al peligro",
      "Evasión del vacío o del malestar emocional",
    ],
    symptoms: [
      "Escalar el nivel de riesgo para sentir lo mismo",
      "Aburrimiento intenso en la vida normal",
      "Ignorar las consecuencias para uno y los demás",
      "Lesiones o sustos recurrentes que no frenan la conducta",
    ],
    solutions: [
      "Canalizar la intensidad en deportes de riesgo regulados",
      "Trabajar la tolerancia al aburrimiento y el vacío",
      "Terapia para la impulsividad y la búsqueda de sensaciones",
      "Construir fuentes de sentido sostenibles",
    ],
  },
  tatuajes: {
    info: "Tatuajes compulsivos. Tatuarse de forma impulsiva para regular emociones o llenar un vacío, más por la descarga del momento que por el diseño en sí.",
    causes: [
      "Regulación de ansiedad mediante la experiencia y el dolor",
      "Búsqueda de identidad o control sobre el cuerpo",
      "Impulsividad y decisiones poco meditadas",
      "Refuerzo por la atención o la novedad",
    ],
    symptoms: [
      "Tatuarse por impulso, sin pensarlo, de forma repetida",
      "Arrepentimiento posterior frecuente",
      "Gasto desproporcionado o problemas económicos",
      "Usar el tatuaje para tapar malestar emocional",
    ],
    solutions: [
      "Aplicar una regla de espera antes de cada tatuaje",
      "Identificar la emoción que dispara el impulso",
      "Buscar otras vías de expresión y de control del cuerpo",
      "Terapia si encubre ansiedad o vacío",
    ],
  },
  cirugias: {
    info: "Adicción a la cirugía estética. Operarse repetidamente buscando una perfección inalcanzable, a menudo ligada a una percepción distorsionada del propio cuerpo.",
    causes: [
      "Insatisfacción corporal persistente (posible dismorfia)",
      "Presión estética de redes y entorno",
      "Autoestima ligada a la apariencia",
      "Creencia de que el siguiente retoque traerá la felicidad",
    ],
    symptoms: [
      "Ver 'defectos' donde otros no los ven",
      "Encadenar operaciones sin sentirse satisfecho/a",
      "Gasto y riesgos médicos crecientes",
      "Malestar emocional que no mejora con cada cirugía",
    ],
    solutions: [
      "Evaluación psicológica de dismorfia corporal antes de operar",
      "Terapia para la imagen corporal y la autoestima",
      "Pausar nuevas intervenciones y revisar expectativas",
      "Reducir la exposición a contenidos de comparación",
    ],
  },
  religiosidad: {
    info: "Religiosidad obsesiva (escrupulosidad). Rituales y dudas religiosas compulsivas que, en vez de dar paz, generan angustia y culpa constantes.",
    causes: [
      "Rasgos obsesivo-compulsivos aplicados a lo espiritual",
      "Miedo intenso al castigo o al pecado",
      "Necesidad de certeza moral absoluta",
      "Crianza muy rígida en lo religioso",
    ],
    symptoms: [
      "Rezos o rituales repetidos para 'hacerlo bien'",
      "Culpa desproporcionada por pensamientos o actos menores",
      "Dudas constantes sobre la propia fe o pureza",
      "Angustia en lugar de consuelo en la práctica",
    ],
    solutions: [
      "Terapia cognitivo-conductual para la escrupulosidad (TOC)",
      "Diferenciar fe sana de ritual ansioso",
      "Acompañamiento espiritual equilibrado y no culpabilizador",
      "Tratar la ansiedad y la necesidad de certeza",
    ],
  },
  autoayuda: {
    info: "Autoayuda compulsiva. Consumir sin parar libros, cursos y métodos de mejora personal como forma de sentir que se avanza, sin llegar a aplicar nada.",
    causes: [
      "Sensación de progreso sin asumir el riesgo de actuar",
      "Búsqueda del método o 'gurú' definitivo",
      "Evitar el malestar de los cambios reales",
      "Insatisfacción crónica con uno mismo",
    ],
    symptoms: [
      "Saltar de método en método sin terminar ninguno",
      "Acumular cursos y libros sin aplicarlos",
      "Sentirse motivado al consumir y vacío al actuar",
      "Postergar la vida real esperando 'estar listo'",
    ],
    solutions: [
      "Pausar el consumo y aplicar UNA sola cosa a la vez",
      "Medir progreso por acciones, no por contenido consumido",
      "Tolerar la incomodidad del cambio real",
      "Acompañamiento que pase del saber al hacer",
    ],
  },
  noticias: {
    info: "Doomscrolling de noticias. Consumo compulsivo de información negativa que da una falsa sensación de control pero alimenta ansiedad, miedo y desesperanza.",
    causes: [
      "Necesidad de control ante un mundo incierto",
      "Sesgo del cerebro hacia lo negativo y la amenaza",
      "Titulares y algoritmos diseñados para alarmar",
      "Hábito de llenar tiempos muertos con el móvil",
    ],
    symptoms: [
      "Pasar horas leyendo malas noticias sin parar",
      "Ansiedad, insomnio y sensación de catástrofe",
      "Revisar titulares a primera y última hora del día",
      "Sentir que 'hay que estar informado' aunque haga daño",
    ],
    solutions: [
      "Horarios y fuentes limitadas para informarse",
      "Quitar apps de noticias del inicio y las alertas",
      "Sustituir el scroll por lectura o contenido positivo",
      "Distinguir informarse de rumiar la catástrofe",
    ],
  },
  citas_apps: {
    info: "Uso compulsivo de apps de citas. El swipe infinito y las recompensas variables (matches, mensajes) enganchan más que la búsqueda real de pareja.",
    causes: [
      "Validación inmediata vía matches y likes",
      "Recompensa variable que imita una tragaperras",
      "Miedo a la soledad y al rechazo cara a cara",
      "Catálogo infinito que dificulta elegir y comprometerse",
    ],
    symptoms: [
      "Hacer swipe durante horas sin intención real de quedar",
      "Sentir vacío pese a muchos matches",
      "Comparación y autoestima atadas a la respuesta de la app",
      "Saltar de conversación en conversación sin profundizar",
    ],
    solutions: [
      "Límites de tiempo y desinstalar temporalmente",
      "Pasar pronto del chat a un encuentro real o descartar",
      "Trabajar la autoestima fuera de la validación digital",
      "Buscar vínculos también en entornos offline",
    ],
  },

  // ─── Alimentarias ───
  azucar: {
    info: "Consumo compulsivo de azúcar. Los azúcares añadidos activan el circuito de recompensa y generan picos y caídas de glucosa que disparan más antojos.",
    causes: [
      "Azúcar oculto en la mayoría de productos procesados",
      "Uso del dulce para calmar estrés y emociones",
      "Picos de glucosa que provocan más antojos a las horas",
      "Asociación cultural del dulce con premio y afecto",
    ],
    symptoms: [
      "Antojos intensos de dulce, sobre todo por la tarde/noche",
      "Bajones de energía y mal humor entre comidas",
      "Comer dulce sin hambre real, de forma automática",
      "Dificultad para parar una vez que se empieza",
    ],
    solutions: [
      "Reducir gradualmente y leer etiquetas (azúcares añadidos)",
      "Comidas con proteína y fibra para estabilizar la glucosa",
      "Tener fruta a mano y quitar el dulce de la vista",
      "Identificar el antojo emocional y darle otra salida",
    ],
  },
  chocolate: {
    info: "Antojo compulsivo de chocolate. Combina azúcar, grasa y compuestos que elevan el ánimo, lo que lo convierte en un recurso frecuente para regular emociones.",
    causes: [
      "Mezcla de azúcar y grasa muy reforzante para el cerebro",
      "Uso como 'consuelo' ante estrés, tristeza o cansancio",
      "Antojos hormonales en ciertos momentos del ciclo",
      "Disponibilidad constante y porciones pequeñas y fáciles",
    ],
    symptoms: [
      "Necesidad diaria de chocolate para sentirse bien",
      "Comer más de lo previsto una y otra vez",
      "Antojos ligados a estados de ánimo concretos",
      "Culpa después de los atracones de chocolate",
    ],
    solutions: [
      "Elegir chocolate negro y porciones medidas conscientes",
      "Atender la emoción detrás del antojo",
      "No tener grandes cantidades almacenadas en casa",
      "Saborear despacio en vez de comer en automático",
    ],
  },
  comida_rapida: {
    info: "Dependencia de la comida rápida. Los ultraprocesados están diseñados para ser hiperpalatables (sal, grasa y azúcar) y disparar el consumo más allá del hambre.",
    causes: [
      "Diseño 'adictivo' de sabor, textura y precio",
      "Comodidad y rapidez frente a cocinar",
      "Publicidad constante y entrega a domicilio inmediata",
      "Asociación con premio, prisa o socialización",
    ],
    symptoms: [
      "Recurrir a fast food varias veces por semana",
      "Antojos intensos de sabores intensos y grasos",
      "Comer más de la cuenta sin saciarse de verdad",
      "Malestar digestivo y culpa recurrentes",
    ],
    solutions: [
      "Planificar comidas y dejar opciones listas en casa",
      "Borrar apps de delivery o limitar su uso",
      "Comer despacio y prestar atención a la saciedad",
      "Sustituir gradualmente por versiones caseras",
    ],
  },
  sal: {
    info: "Consumo excesivo de snacks salados. La combinación de sal y crujiente de los ultraprocesados engancha y favorece comer sin control frente a la pantalla.",
    causes: [
      "Sabor salado y textura diseñados para no parar",
      "Picoteo automático mientras se ve TV o se trabaja",
      "Disponibilidad de paquetes grandes y baratos",
      "Uso del snack para calmar aburrimiento o ansiedad",
    ],
    symptoms: [
      "Terminar paquetes enteros sin darse cuenta",
      "Antojo frecuente de algo salado y crujiente",
      "Retención de líquidos y sed constante",
      "Picar fuera de horas de comida de forma habitual",
    ],
    solutions: [
      "Servir porciones en un plato, no comer del paquete",
      "Tener alternativas crujientes y sanas a mano",
      "Romper la asociación pantalla-picoteo",
      "Reducir sal poco a poco para reeducar el paladar",
    ],
  },
  refrescos: {
    info: "Consumo compulsivo de refrescos azucarados. Una sola lata puede superar el azúcar diario recomendado, y su efecto refrescante refuerza el hábito.",
    causes: [
      "Alto contenido de azúcar (o cafeína) muy reforzante",
      "Hábito de acompañar las comidas con refresco",
      "Publicidad y disponibilidad en todas partes",
      "Sed mal interpretada que se calma con refresco",
    ],
    symptoms: [
      "Beber varias latas o vasos al día",
      "Antojo y dolor de cabeza si no se consume",
      "Rechazo del agua sola por sosa",
      "Problemas dentales y de peso asociados",
    ],
    solutions: [
      "Sustituir progresivamente por agua con gas o saborizada natural",
      "No comprarlos para tener en casa",
      "Asociar la sed con agua, no con refresco",
      "Reducir cantidad por etapas para dejar el azúcar",
    ],
  },
  carbohidratos: {
    info: "Consumo excesivo de carbohidratos refinados. Pan, pasta y harinas blancas elevan rápido la glucosa y generan un ciclo de antojo y bajón parecido al del azúcar.",
    causes: [
      "Subida y caída rápida de glucosa que pide más",
      "Comodidad y bajo costo de los productos refinados",
      "Uso de la 'comida reconfortante' para calmar emociones",
      "Porciones grandes normalizadas",
    ],
    symptoms: [
      "Antojo constante de pan, pasta o harinas",
      "Somnolencia y bajón después de comer",
      "Comer grandes cantidades sin saciarse",
      "Picar harinas entre comidas de forma automática",
    ],
    solutions: [
      "Priorizar integrales, proteína y verduras en el plato",
      "Comidas equilibradas que estabilicen la glucosa",
      "Porciones conscientes y comer despacio",
      "Identificar el componente emocional del antojo",
    ],
  },
  lacteos: {
    info: "Consumo excesivo de lácteos. Quesos y productos lácteos muy palatables pueden consumirse de forma compulsiva, sumando grasas y calorías sin control.",
    causes: [
      "Alta palatabilidad de quesos y cremas",
      "Hábito y disponibilidad en casi todas las comidas",
      "Uso como snack rápido y reconfortante",
      "Porciones poco conscientes",
    ],
    symptoms: [
      "Picar queso u otros lácteos de forma constante",
      "Malestar digestivo recurrente (hinchazón, gases)",
      "Dificultad para reducir pese a las molestias",
      "Comer lácteos sin hambre real",
    ],
    solutions: [
      "Medir porciones y no comer directo del envase",
      "Probar alternativas y variar las fuentes de proteína",
      "Observar si hay intolerancia y ajustar",
      "Romper la asociación lácteo-snack automático",
    ],
  },
  helado: {
    info: "Consumo compulsivo de helado. Frío, dulce y cremoso, combina azúcar y grasa con un efecto reconfortante que invita al consumo nocturno y emocional.",
    causes: [
      "Combinación azúcar-grasa muy reforzante",
      "Ritual de consuelo nocturno frente a la pantalla",
      "Asociación con premio y relax",
      "Disponibilidad de envases grandes en el congelador",
    ],
    symptoms: [
      "Comer helado casi todas las noches",
      "Terminar envases grandes de una sentada",
      "Antojo ligado a estados de ánimo o estrés",
      "Culpa después del atracón",
    ],
    solutions: [
      "No almacenar grandes envases; comprar porciones individuales",
      "Atender la emoción detrás del ritual nocturno",
      "Sustituir por opciones más ligeras (fruta congelada, yogur)",
      "Crear una rutina de relax que no gire en torno a la comida",
    ],
  },
  postres: {
    info: "Antojo diario de postres y repostería. El dulce tras las comidas se vuelve una necesidad automática más que un gusto ocasional.",
    causes: [
      "Hábito de 'cerrar' cada comida con algo dulce",
      "Azúcar como recompensa y regulación emocional",
      "Repostería muy accesible y atractiva",
      "Picos de glucosa que reactivan el antojo",
    ],
    symptoms: [
      "Necesitar postre después de cada comida",
      "Antojos de dulce a media tarde difíciles de resistir",
      "Comer repostería sin hambre, por costumbre",
      "Sensación de que 'falta algo' sin el dulce",
    ],
    solutions: [
      "Romper el automatismo: esperar 20 min tras comer",
      "Cerrar la comida con fruta o infusión",
      "Reservar el postre para ocasiones, no a diario",
      "Reeducar el paladar bajando el azúcar poco a poco",
    ],
  },
  anorexia: {
    info: "Restricción alimentaria patológica. Conducta de comer muy poco y miedo intenso a subir de peso, con grave riesgo físico; requiere atención profesional especializada.",
    causes: [
      "Miedo intenso al peso y distorsión de la imagen corporal",
      "Necesidad de control en medio del malestar emocional",
      "Presión estética y comparación social",
      "Perfeccionismo y autoexigencia extrema",
    ],
    symptoms: [
      "Restricción severa de comida y conteo obsesivo",
      "Pérdida de peso marcada y miedo a engordar",
      "Verse con sobrepeso pese a estar muy delgado/a",
      "Aislamiento social en torno a la comida",
    ],
    solutions: [
      "Atención médica urgente: hay riesgo vital",
      "Tratamiento multidisciplinar (médico, nutrición, psicología)",
      "Terapia para imagen corporal y control",
      "Apoyo familiar y supervisión cercana",
    ],
  },
  bulimia: {
    info: "Ciclo de atracón y purga. Episodios de ingesta descontrolada seguidos de conductas compensatorias (vómito, laxantes, ayuno) con grave impacto en la salud.",
    causes: [
      "Restricción extrema que dispara el atracón",
      "Regulación emocional mediante comida y purga",
      "Miedo al peso e imagen corporal distorsionada",
      "Vergüenza y secretismo que mantienen el ciclo",
    ],
    symptoms: [
      "Atracones seguidos de vómito, laxantes o ayuno",
      "Idas frecuentes al baño tras comer",
      "Daño dental, garganta irritada y desbalances",
      "Culpa y secretismo intensos",
    ],
    solutions: [
      "Atención médica por las complicaciones del purgado",
      "Comer regularmente para romper el ciclo restricción-atracón",
      "Terapia especializada en TCA (TCC-E)",
      "Apoyo profesional de nutrición no-restrictiva",
    ],
  },
  ortorexia: {
    info: "Ortorexia. Obsesión por comer 'puro' o 'perfecto' que, lejos de ser salud, se vuelve rígida, ansiosa y aislante.",
    causes: [
      "Perfeccionismo aplicado a la alimentación",
      "Información extrema de dietas en redes",
      "Necesidad de control y pureza",
      "Miedo a la enfermedad o a la 'comida mala'",
    ],
    symptoms: [
      "Reglas alimentarias cada vez más estrictas",
      "Ansiedad o culpa al salirse de la dieta 'limpia'",
      "Evitar comidas sociales por miedo a los ingredientes",
      "Tiempo excesivo planificando y vigilando la comida",
    ],
    solutions: [
      "Flexibilizar reglas de forma gradual y guiada",
      "Terapia para perfeccionismo y ansiedad alimentaria",
      "Recuperar el placer y lo social de comer",
      "Filtrar fuentes y dejar dietas extremas de redes",
    ],
  },
  cafe_postre: {
    info: "Ritual compulsivo de café con dulce. La combinación de cafeína y azúcar se convierte en un hábito diario difícil de saltarse sin sentir que 'falta algo'.",
    causes: [
      "Doble recompensa de cafeína + azúcar",
      "Ritual social y pausa placentera del día",
      "Asociación fuerte café-dulce ya automatizada",
      "Necesidad de un 'premio' a media jornada",
    ],
    symptoms: [
      "No poder tomar café sin acompañarlo de dulce",
      "Repetir el combo varias veces al día",
      "Antojo e inquietud si falta el ritual",
      "Acumular azúcar y calorías sin notarlo",
    ],
    solutions: [
      "Separar los dos hábitos: café solo algunos días",
      "Sustituir el dulce por fruta o chocolate negro",
      "Conservar el ritual de pausa sin el azúcar",
      "Reducir frecuencia poco a poco",
    ],
  },
  salsas: {
    info: "Uso excesivo de salsas y aderezos. Ketchup, mayonesa y similares aportan azúcar, sodio y grasa ocultos, y refuerzan comer más cantidad.",
    causes: [
      "Realce intenso del sabor que engancha",
      "Hábito de añadir salsa a casi todo",
      "Azúcar y sodio ocultos muy palatables",
      "Comer más cantidad gracias al extra de sabor",
    ],
    symptoms: [
      "Necesitar salsa para poder comer cualquier plato",
      "Usar grandes cantidades de forma automática",
      "Antojo de sabores intensos constantemente",
      "Sumar calorías y sodio sin darse cuenta",
    ],
    solutions: [
      "Medir las porciones de salsa en vez de echar libremente",
      "Probar alternativas caseras bajas en azúcar y sodio",
      "Reeducar el paladar reduciendo gradualmente",
      "Condimentar con especias en lugar de salsas procesadas",
    ],
  },

  // ─── Digitales ───
  tiktok: {
    info: "Uso compulsivo de TikTok. El feed de videos cortos con recompensa impredecible está diseñado para encadenar visualizaciones y hacer perder la noción del tiempo.",
    causes: [
      "Algoritmo hiperpersonalizado que acierta lo que te engancha",
      "Videos cortos con recompensa variable e inmediata",
      "Scroll infinito sin puntos de parada naturales",
      "Uso para evadir aburrimiento, ansiedad o tareas",
    ],
    symptoms: [
      "Abrir la app para 'un momento' y perder horas",
      "Mirar videos hasta tarde sacrificando el sueño",
      "Dificultad para concentrarse en contenidos largos",
      "Ansiedad o inquietud sin el móvil cerca",
    ],
    solutions: [
      "Límites de tiempo de la app y recordatorios",
      "Desactivar reproducción automática y notificaciones",
      "Quitar la app del inicio o desinstalarla por temporadas",
      "Sustituir los ratos muertos por otra actividad preparada",
    ],
  },
  instagram: {
    info: "Uso problemático de Instagram. Combina scroll infinito con comparación social constante, alimentando la búsqueda de validación a través de likes y seguidores.",
    causes: [
      "Comparación con vidas filtradas e idealizadas",
      "Validación social vía likes, vistas y comentarios",
      "Stories y reels diseñados para revisar a cada rato",
      "Miedo a perderse lo que publican los demás",
    ],
    symptoms: [
      "Revisar la app decenas de veces al día",
      "Ánimo atado al rendimiento de lo que publicas",
      "Comparación que baja la autoestima",
      "Scroll automático en cualquier hueco",
    ],
    solutions: [
      "Depurar a quién sigues (cuentas que no te hagan mal)",
      "Quitar contador de likes y silenciar notificaciones",
      "Horarios fijos de uso y app fuera del dormitorio",
      "Trabajar la autoestima fuera de la validación digital",
    ],
  },
  youtube: {
    info: "Uso compulsivo de YouTube. La reproducción automática y las recomendaciones encadenan video tras video, convirtiendo una búsqueda puntual en horas de consumo.",
    causes: [
      "Autoplay y recomendaciones que nunca se acaban",
      "Contenido infinito para cualquier interés o estado",
      "Uso como ruido de fondo o evasión",
      "Sensación de 'estar aprendiendo' que justifica el exceso",
    ],
    symptoms: [
      "Maratones de videos que desplazan el sueño",
      "Entrar a buscar algo y terminar en temas inconexos",
      "Necesidad de tener un video puesto siempre",
      "Procrastinar tareas viendo 'solo uno más'",
    ],
    solutions: [
      "Desactivar la reproducción automática",
      "Ver con objetivo concreto y cerrar al terminar",
      "Temporizadores y recordatorios de pausa",
      "Sustituir el consumo pasivo por contenido elegido a propósito",
    ],
  },
  netflix: {
    info: "Binge-watching de series y streaming. El autoplay del siguiente episodio y los finales en suspenso empujan a seguir viendo más allá de lo planeado.",
    causes: [
      "Reproducción automática del siguiente episodio",
      "Tramas con cliffhangers diseñados para encadenar",
      "Uso para evadir estrés o vacío",
      "Catálogo enorme y barato siempre disponible",
    ],
    symptoms: [
      "Ver varios episodios o temporadas de una sentada",
      "Trasnochar viendo series entre semana",
      "Posponer obligaciones y planes por seguir viendo",
      "Sensación de pereza y culpa después",
    ],
    solutions: [
      "Desactivar el autoplay del siguiente episodio",
      "Fijar de antemano cuántos episodios ver",
      "No usar la TV/pantalla en la cama",
      "Alternar con otras actividades de ocio activo",
    ],
  },
  whatsapp: {
    info: "Uso compulsivo de mensajería. La expectativa de respuestas y la presión de estar siempre disponible llevan a revisar el chat decenas de veces al día.",
    causes: [
      "Recompensa variable de mensajes y notificaciones",
      "Presión social de responder al instante",
      "Grupos numerosos con actividad constante",
      "Ansiedad por no perderse nada importante",
    ],
    symptoms: [
      "Revisar el chat compulsivamente, incluso conduciendo",
      "Ansiedad ante mensajes no respondidos",
      "Interrumpir tareas con cada notificación",
      "Sensación de no poder desconectar nunca",
    ],
    solutions: [
      "Silenciar grupos y desactivar notificaciones no esenciales",
      "Bloques sin móvil para tareas y descanso",
      "Gestionar expectativas: responder por tandas, no al instante",
      "Salir de grupos que no aportan",
    ],
  },
  email: {
    info: "Revisión compulsiva del correo. Mirar la bandeja cada pocos minutos da falsa sensación de productividad pero fragmenta la atención y aumenta el estrés.",
    causes: [
      "Cultura de respuesta inmediata en el trabajo",
      "Notificaciones que interrumpen constantemente",
      "Sensación de control al 'estar al día'",
      "Miedo a perderse algo urgente",
    ],
    symptoms: [
      "Abrir el correo cada pocos minutos sin necesidad",
      "Revisarlo fuera del horario laboral y en vacaciones",
      "Dificultad para concentrarse en tareas largas",
      "Ansiedad ante la bandeja llena",
    ],
    solutions: [
      "Revisar el correo en 2-3 momentos fijos del día",
      "Desactivar notificaciones de email",
      "Bloques de trabajo profundo sin la bandeja abierta",
      "Plantillas y filtros para procesar más rápido",
    ],
  },
  celular: {
    info: "Nomofobia: ansiedad por estar sin el celular. El teléfono concentra tantas recompensas que su ausencia genera inquietud y revisión constante.",
    causes: [
      "El móvil reúne todas las recompensas en un solo lugar",
      "Hábito de llenar cualquier pausa con la pantalla",
      "Miedo a estar incomunicado o perderse algo",
      "Notificaciones que reclaman atención sin parar",
    ],
    symptoms: [
      "Revisar el teléfono sin motivo decenas de veces",
      "Ansiedad si la batería baja o no se tiene cerca",
      "Llevarlo a todas partes, incluso al baño",
      "Sentir vibraciones o avisos que no existen",
    ],
    solutions: [
      "Zonas y horas sin móvil (comidas, dormitorio)",
      "Pantalla en escala de grises y menos notificaciones",
      "Dejar el teléfono lejos al concentrarse o dormir",
      "Reaprender a tolerar el aburrimiento sin pantalla",
    ],
  },
  internet: {
    info: "Uso problemático de internet. Navegar sin propósito durante horas saltando de página en página como forma de evasión y de llenar el tiempo.",
    causes: [
      "Acceso ilimitado a contenido novedoso",
      "Evasión de tareas, emociones o aburrimiento",
      "Curiosidad infinita que salta de un enlace a otro",
      "Ausencia de límites naturales al navegar",
    ],
    symptoms: [
      "Pasar horas navegando sin recordar qué buscabas",
      "Posponer obligaciones por seguir conectado",
      "Inquietud cuando no hay conexión",
      "Cansancio mental y poca sensación de logro",
    ],
    solutions: [
      "Navegar con un objetivo y cerrar al cumplirlo",
      "Bloqueadores de webs y límites de tiempo",
      "Planificar el día para reducir el 'vagar' online",
      "Sustituir la evasión por actividades concretas",
    ],
  },
  memes: {
    info: "Consumo infinito de humor digital. Los memes y clips graciosos ofrecen pequeñas dosis de placer constantes que encadenan el scroll sin fin.",
    causes: [
      "Microrrecompensas de risa rápidas y continuas",
      "Uso para evadir estrés y aburrimiento",
      "Compartir y comentar como vínculo social",
      "Feeds diseñados para no terminar nunca",
    ],
    symptoms: [
      "Pasar horas viendo contenido humorístico sin parar",
      "Recurrir a memes para no enfrentar tareas o emociones",
      "Dificultad para mantener atención sostenida",
      "Sensación de tiempo perdido después",
    ],
    solutions: [
      "Límites de tiempo y feeds específicos",
      "Detectar el uso evasivo y darle otra salida",
      "Sustituir por humor compartido en persona",
      "Quitar las apps del inicio para frenar el automatismo",
    ],
  },
  foros: {
    info: "Lectura compulsiva de foros y Reddit. Hilos interminables y debates constantes enganchan a leer, responder y volver a comprobar respuestas sin parar.",
    causes: [
      "Curiosidad infinita y temas para todos los intereses",
      "Recompensa de votos y respuestas a tus comentarios",
      "Sensación de pertenencia a comunidades",
      "Debates que invitan a 'tener la última palabra'",
    ],
    symptoms: [
      "Horas leyendo hilos sin propósito claro",
      "Revisar respuestas y votos compulsivamente",
      "Enredarse en discusiones que generan estrés",
      "Procrastinar leyendo 'un hilo más'",
    ],
    solutions: [
      "Limitar tiempo y comunidades que sigues",
      "Evitar discusiones que solo generan malestar",
      "Horarios concretos de lectura, no continua",
      "Sustituir por lectura con principio y fin",
    ],
  },
  gaming_movil: {
    info: "Adicción a juegos móviles gacha. Loot boxes, recompensas diarias y microtransacciones explotan la recompensa variable y la presión a gastar dinero real.",
    causes: [
      "Recompensa variable de loot boxes (azar real)",
      "Eventos y recompensas diarias que crean obligación",
      "Presión social y competición por ranking",
      "Microtransacciones diseñadas para gastar 'un poco más'",
    ],
    symptoms: [
      "Jugar para no perder rachas o eventos diarios",
      "Gastar dinero real de forma recurrente",
      "Ansiedad por no completar tareas del juego",
      "Jugar a escondidas o más de lo previsto",
    ],
    solutions: [
      "Eliminar datos de pago del juego y la tienda",
      "Desactivar recordatorios y eventos diarios",
      "Límites de tiempo estrictos o desinstalar",
      "Sustituir por juegos sin azar ni microtransacciones",
    ],
  },
  twitch: {
    info: "Consumo compulsivo de streams en vivo. La sensación de comunidad en tiempo real y el miedo a perderse momentos únicos llevan a ver horas seguidas.",
    causes: [
      "Directo en tiempo real con sensación de 'estar ahí'",
      "Comunidad y chat que generan pertenencia",
      "Miedo a perderse momentos irrepetibles del directo",
      "Compañía ante la soledad o el aburrimiento",
    ],
    symptoms: [
      "Ver streams durante horas, a veces de fondo todo el día",
      "Trasnochar para no perderse directos",
      "Descuidar tareas y vínculos reales",
      "Gastar en suscripciones y donaciones impulsivas",
    ],
    solutions: [
      "Elegir qué ver con intención, no dejarlo de fondo",
      "Horarios de visionado y límites de gasto",
      "Buscar comunidad y compañía también offline",
      "Ver resúmenes en vez del directo completo",
    ],
  },
  podcasts: {
    info: "Consumo excesivo de podcasts. El audio constante llena todos los silencios; aunque parece productivo, puede volverse una evasión que impide estar a solas con uno mismo.",
    causes: [
      "Sensación de aprovechar el tiempo 'aprendiendo'",
      "Incomodidad con el silencio y los propios pensamientos",
      "Compañía constante ante la soledad",
      "Contenido infinito siempre disponible",
    ],
    symptoms: [
      "No poder hacer nada sin un audio de fondo",
      "Ansiedad o incomodidad con el silencio",
      "Acumular episodios pendientes con presión por 'ponerse al día'",
      "Escuchar sin retener realmente nada",
    ],
    solutions: [
      "Reservar ratos de silencio a propósito",
      "Escuchar con atención y en momentos concretos",
      "Reducir suscripciones y soltar la presión de la cola",
      "Permitirse estar a solas con los propios pensamientos",
    ],
  },
  ia_chatbots: {
    info: "Dependencia emocional de chatbots de IA. La disponibilidad y la respuesta siempre amable pueden sustituir vínculos humanos y dificultar tolerar la frustración real.",
    causes: [
      "Disponibilidad 24/7 sin juicio ni conflicto",
      "Respuestas a medida que refuerzan el uso",
      "Soledad o dificultad en relaciones humanas",
      "Comodidad frente a la complejidad del vínculo real",
    ],
    symptoms: [
      "Recurrir al chatbot antes que a personas reales",
      "Pasar muchas horas conversando con la IA",
      "Malestar o vacío sin acceso a la app",
      "Menor tolerancia a la fricción de las relaciones humanas",
    ],
    solutions: [
      "Usar la IA como herramienta, no como sustituto afectivo",
      "Fomentar vínculos y conversaciones reales",
      "Límites de tiempo de uso conversacional",
      "Terapia si tapa soledad o ansiedad social",
    ],
  },
  notificaciones: {
    info: "Reacción compulsiva a las notificaciones. Cada aviso entrena una respuesta automática (mirar el móvil) que fragmenta la atención todo el día.",
    causes: [
      "Refuerzo pavloviano de cada sonido o vibración",
      "Apps diseñadas para reclamar atención constante",
      "Miedo a perderse algo importante",
      "Hábito de revisar ante cualquier estímulo",
    ],
    symptoms: [
      "Interrumpir todo para mirar cada notificación",
      "Sentir vibraciones fantasma inexistentes",
      "Incapacidad de mantener foco prolongado",
      "Ansiedad ante el icono de avisos pendientes",
    ],
    solutions: [
      "Desactivar la mayoría de notificaciones (dejar solo críticas)",
      "Modo concentración y no molestar por bloques",
      "Agrupar avisos en horarios concretos",
      "Quitar insignias y sonidos de las apps",
    ],
  },
  selfies: {
    info: "Obsesión con selfies y autoimagen. Tomar y editar fotos de uno mismo de forma compulsiva, ligada a la búsqueda de validación y a la insatisfacción corporal.",
    causes: [
      "Validación social mediante likes y comentarios",
      "Comparación con imágenes editadas e idealizadas",
      "Insatisfacción con la propia imagen (posible dismorfia)",
      "Filtros que distorsionan la autopercepción",
    ],
    symptoms: [
      "Tomar y editar decenas de fotos antes de publicar",
      "Ansiedad por la respuesta a las publicaciones",
      "Verse mal sin filtros o edición",
      "Tiempo excesivo dedicado a la autoimagen",
    ],
    solutions: [
      "Reducir filtros y edición de forma progresiva",
      "Trabajar autoestima e imagen corporal en terapia",
      "Limitar publicaciones y comparación en redes",
      "Buscar valor en cualidades más allá de la apariencia",
    ],
  },
  influencers: {
    info: "Seguimiento obsesivo de influencers. Ligar la vida emocional a creadores idealizados genera comparación, gasto y dependencia de su contenido.",
    causes: [
      "Idealización de vidas perfectas y aspiracionales",
      "Sensación de cercanía y 'amistad' parasocial",
      "Comparación constante con su estilo de vida",
      "Marketing que empuja a imitar y comprar",
    ],
    symptoms: [
      "Revisar a tus referentes muchas veces al día",
      "Comparar tu vida con la suya y sentirte peor",
      "Comprar lo que recomiendan por impulso",
      "Estado de ánimo afectado por su contenido",
    ],
    solutions: [
      "Depurar a quién sigues según cómo te haga sentir",
      "Recordar que muestran una versión editada de su vida",
      "Limitar el tiempo y el gasto inducido",
      "Cultivar referentes y metas propias y realistas",
    ],
  },
  ecommerce: {
    info: "Compras online compulsivas. El 1-click, las ofertas constantes y la entrega rápida convierten la compra en una recompensa fácil para regular emociones.",
    causes: [
      "Compra a un clic sin fricción que invite a frenar",
      "Ofertas, cupones y urgencia artificial constantes",
      "Dopamina de la compra y la espera del paquete",
      "Uso del consumo para calmar emociones",
    ],
    symptoms: [
      "Pedidos frecuentes de cosas poco necesarias",
      "Paquetes sin abrir acumulándose",
      "Gasto creciente y mentiras sobre las compras",
      "Euforia breve seguida de culpa",
    ],
    solutions: [
      "Regla de espera de 72 horas antes de comprar",
      "Eliminar tarjetas guardadas y desactivar 1-click",
      "Cancelar emails y notificaciones de ofertas",
      "Lista de deseos en vez de compra inmediata",
    ],
  },
  fomo: {
    info: "FOMO digital. Miedo persistente a perderse algo que ocurre online, que obliga a revisar redes constantemente y dificulta estar presente en el momento real.",
    causes: [
      "Flujo infinito de lo que hacen y publican los demás",
      "Comparación social permanente",
      "Notificaciones que crean sensación de urgencia",
      "Autoestima ligada a estar 'al día' y conectado",
    ],
    symptoms: [
      "Revisar redes por miedo a perderse algo",
      "Dificultad para desconectar y estar presente",
      "Ansiedad al no poder mirar el móvil",
      "Comparación que genera insatisfacción constante",
    ],
    solutions: [
      "Practicar 'JOMO': el placer de perderse cosas a propósito",
      "Periodos planificados de desconexión digital",
      "Desactivar notificaciones que generan urgencia",
      "Enfocarse en estar presente en lo que se hace ahora",
    ],
  },

  // ─── Emocionales ───
  drama: {
    info: "Adicción al drama emocional. Buscar o generar conflicto e intensidad para sentirse vivo; la calma se vive como vacío o aburrimiento.",
    causes: [
      "Asociar intensidad emocional con sentirse vivo",
      "Patrones aprendidos de relaciones caóticas",
      "Evasión del vacío mediante el conflicto",
      "Refuerzo por la atención que genera el drama",
    ],
    symptoms: [
      "Crear o magnificar conflictos de forma recurrente",
      "Aburrimiento o inquietud cuando todo está en calma",
      "Relaciones marcadas por subidas y bajadas intensas",
      "Sensación de protagonismo en medio del caos",
    ],
    solutions: [
      "Aprender a tolerar la calma sin vivirla como vacío",
      "Detectar el impulso de 'echar leña' y frenarlo",
      "Construir fuentes de sentido estables y tranquilas",
      "Terapia para los patrones relacionales y el vacío",
    ],
  },
  preocupacion: {
    info: "Preocupación crónica. Rumiar problemas una y otra vez con la ilusión de 'resolverlos', cuando en realidad solo aumenta la ansiedad y el agotamiento.",
    causes: [
      "Creencia de que preocuparse 'previene' lo malo",
      "Intolerancia a la incertidumbre",
      "Ansiedad de base y exceso de control mental",
      "Hábito de anticipar siempre lo peor",
    ],
    symptoms: [
      "Dar vueltas a los mismos problemas sin resolverlos",
      "Anticipar catástrofes constantemente",
      "Tensión física, insomnio y fatiga mental",
      "Dificultad para 'apagar' la mente",
    ],
    solutions: [
      "Tiempo acotado de preocupación al día (worry time)",
      "Diferenciar problemas resolubles de los hipotéticos",
      "Pasar de rumiar a un plan de acción concreto",
      "Técnicas de atención plena y manejo de la incertidumbre",
    ],
  },
  victimismo: {
    info: "Victimismo crónico. Construir la identidad alrededor del sufrimiento y la injusticia, lo que da atención y exime de responsabilidad, pero impide avanzar.",
    causes: [
      "Atención y cuidado obtenidos a través del sufrimiento",
      "Evitar la responsabilidad sobre la propia vida",
      "Heridas reales no procesadas que se cronifican",
      "Sensación de impotencia aprendida",
    ],
    symptoms: [
      "Sentirse siempre tratado injustamente",
      "Atribuir todo a causas externas, nunca a uno mismo",
      "Buscar constantemente validación del propio sufrimiento",
      "Rechazar soluciones que implican responsabilizarse",
    ],
    solutions: [
      "Recuperar el foco en lo que sí se puede controlar",
      "Procesar las heridas reales en terapia",
      "Pasar de 'me pasa' a 'qué puedo hacer'",
      "Reforzar pequeñas acciones de agencia personal",
    ],
  },
  ira: {
    info: "Adicción a la ira. Las explosiones de rabia liberan una descarga intensa que alivia momentáneamente la tensión, pero dañan vínculos y se vuelven un patrón.",
    causes: [
      "Descarga rápida de tensión y sensación de poder",
      "Modelos familiares de explosión emocional",
      "Baja tolerancia a la frustración",
      "Emociones de fondo (dolor, miedo) expresadas como ira",
    ],
    symptoms: [
      "Explosiones de rabia desproporcionadas al motivo",
      "Alivio momentáneo seguido de culpa",
      "Conflictos y rupturas recurrentes",
      "Tensión que solo se descarga estallando",
    ],
    solutions: [
      "Reconocer las señales corporales previas y hacer una pausa",
      "Técnicas de regulación (respiración, tiempo fuera)",
      "Identificar la emoción real bajo la ira",
      "Terapia de manejo de la ira y la frustración",
    ],
  },
  celos: {
    info: "Celos obsesivos. Vigilancia y desconfianza constantes hacia la pareja que buscan calmar la inseguridad, pero la aumentan y deterioran la relación.",
    causes: [
      "Inseguridad y miedo intenso al abandono",
      "Apego inseguro y baja autoestima",
      "Experiencias previas de traición no resueltas",
      "Necesidad de control sobre la pareja",
    ],
    symptoms: [
      "Revisar mensajes, ubicaciones y redes de la pareja",
      "Interrogatorios y desconfianza constantes",
      "Ansiedad intensa ante la separación",
      "Conflictos repetidos por celos infundados",
    ],
    solutions: [
      "Trabajar la autoestima y el apego en terapia",
      "Frenar las conductas de comprobación (no revisar)",
      "Tolerar la incertidumbre sin buscar 'pruebas'",
      "Comunicación honesta en lugar de vigilancia",
    ],
  },
  aprobacion: {
    info: "Búsqueda compulsiva de aprobación. Necesidad de gustar y agradar a todos que lleva a anularse, decir siempre que sí y depender del juicio ajeno.",
    causes: [
      "Autoestima basada en la validación externa",
      "Miedo al rechazo y al conflicto",
      "Aprendizaje de que el valor depende de complacer",
      "Inseguridad sobre el propio criterio",
    ],
    symptoms: [
      "Decir que sí aunque no quieras, por miedo a decepcionar",
      "Ansiedad intensa ante la crítica o el rechazo",
      "Anular gustos y opiniones para encajar",
      "Necesitar confirmación constante de los demás",
    ],
    solutions: [
      "Practicar poner límites y decir 'no' progresivamente",
      "Construir autoestima desde valores propios",
      "Tolerar la desaprobación sin sentirla como catástrofe",
      "Terapia para el miedo al rechazo",
    ],
  },
  autocompasion: {
    info: "Autocompasión rumiante. Reciclar la propia desgracia una y otra vez, lo que da consuelo momentáneo pero refuerza la identidad de víctima y la pasividad.",
    causes: [
      "Consuelo y atención obtenidos al lamentarse",
      "Evasión de la acción y la responsabilidad",
      "Estados depresivos que sesgan hacia lo negativo",
      "Hábito de rumiar el sufrimiento",
    ],
    symptoms: [
      "Repasar mentalmente lo mal que está todo",
      "Lamentarse sin pasar a la acción",
      "Sensación de impotencia que se retroalimenta",
      "Rechazo de perspectivas o soluciones",
    ],
    solutions: [
      "Distinguir autocompasión sana (amabilidad) de la rumiación",
      "Pasar del lamento a pequeños pasos de acción",
      "Limitar el tiempo dedicado a 'darle vueltas'",
      "Terapia para el ánimo y los patrones de rumiación",
    ],
  },
  comparacion: {
    info: "Comparación social compulsiva. Medirse constantemente con los demás, sobre todo en redes, lo que erosiona la autoestima y genera insatisfacción crónica.",
    causes: [
      "Exposición constante a vidas ajenas idealizadas",
      "Autoestima ligada al estatus relativo",
      "Cultura del logro y la competencia",
      "Inseguridad y necesidad de 'estar a la altura'",
    ],
    symptoms: [
      "Compararse con otros muchas veces al día",
      "Sentirse insuficiente pese a los propios logros",
      "Envidia y desánimo tras ver redes",
      "Minimizar lo propio frente a lo ajeno",
    ],
    solutions: [
      "Reducir la exposición a disparadores de comparación",
      "Compararse con uno mismo, no con los demás",
      "Practicar gratitud y reconocer el propio avance",
      "Trabajar la autoestima desde valores internos",
    ],
  },
  autoexigencia: {
    info: "Autoexigencia tóxica. Sentir que nada de lo que se hace es suficiente; la vara siempre sube y el logro nunca trae descanso ni satisfacción.",
    causes: [
      "Valía personal condicionada al rendimiento",
      "Crianza o entorno muy exigentes",
      "Miedo a no ser suficiente o a defraudar",
      "Comparación constante con un ideal inalcanzable",
    ],
    symptoms: [
      "No disfrutar los logros porque 'pudo ser mejor'",
      "Autocrítica dura y constante",
      "Agotamiento y sensación de no llegar nunca",
      "Subir la vara apenas se alcanza una meta",
    ],
    solutions: [
      "Definir 'suficiente' de antemano y respetarlo",
      "Practicar autocompasión y descanso sin culpa",
      "Separar la valía personal del rendimiento",
      "Terapia para los estándares rígidos internos",
    ],
  },
  queja: {
    info: "Queja crónica. Quejarse de forma constante como modo de relacionarse y de descargar malestar, lo que refuerza el foco negativo y aleja a los demás.",
    causes: [
      "Descarga de malestar y búsqueda de validación",
      "Hábito y patrón aprendido de comunicación",
      "Sesgo atencional hacia lo negativo",
      "Evitar la acción centrándose en el problema",
    ],
    symptoms: [
      "Quejarse de casi todo de forma automática",
      "Conversaciones centradas en lo que está mal",
      "Sensación de alivio breve seguido del mismo malestar",
      "Cansar o alejar a la gente del entorno",
    ],
    solutions: [
      "Practicar pasar de la queja a la propuesta o acción",
      "Ejercicios diarios de gratitud y foco en lo positivo",
      "Detectar el patrón y reformular en positivo",
      "Reservar la queja para lo importante y buscar soluciones",
    ],
  },
};