/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SoporteRouteImport } from './routes/soporte'
import { Route as RetosRouteImport } from './routes/retos'
import { Route as NuevaMetaRouteImport } from './routes/nueva-meta'
import { Route as MasRouteImport } from './routes/mas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EnciclopediaRouteImport } from './routes/enciclopedia'
import { Route as EligeAdiccionRouteImport } from './routes/elige-adiccion'
import { Route as ComunidadRouteImport } from './routes/comunidad'
import { Route as AmigosRouteImport } from './routes/amigos'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SoporteRoute = SoporteRouteImport.update({
  id: '/soporte',
  path: '/soporte',
  getParentRoute: () => rootRouteImport,
} as any)
const RetosRoute = RetosRouteImport.update({
  id: '/retos',
  path: '/retos',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaMetaRoute = NuevaMetaRouteImport.update({
  id: '/nueva-meta',
  path: '/nueva-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EnciclopediaRoute = EnciclopediaRouteImport.update({
  id: '/enciclopedia',
  path: '/enciclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const EligeAdiccionRoute = EligeAdiccionRouteImport.update({
  id: '/elige-adiccion',
  path: '/elige-adiccion',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadRoute = ComunidadRouteImport.update({
  id: '/comunidad',
  path: '/comunidad',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosRoute = AmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/amigos': typeof AmigosRoute
  '/comunidad': typeof ComunidadRoute
  '/elige-adiccion': typeof EligeAdiccionRoute
  '/enciclopedia': typeof EnciclopediaRoute
  '/login': typeof LoginRoute
  '/mas': typeof MasRoute
  '/nueva-meta': typeof NuevaMetaRoute
  '/retos': typeof RetosRoute
  '/soporte': typeof SoporteRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/amigos': typeof AmigosRoute
  '/comunidad': typeof ComunidadRoute
  '/elige-adiccion': typeof EligeAdiccionRoute
  '/enciclopedia': typeof EnciclopediaRoute
  '/login': typeof LoginRoute
  '/mas': typeof MasRoute
  '/nueva-meta': typeof NuevaMetaRoute
  '/retos': typeof RetosRoute
  '/soporte': typeof SoporteRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/amigos': typeof AmigosRoute
  '/comunidad': typeof ComunidadRoute
  '/elige-adiccion': typeof EligeAdiccionRoute
  '/enciclopedia': typeof EnciclopediaRoute
  '/login': typeof LoginRoute
  '/mas': typeof MasRoute
  '/nueva-meta': typeof NuevaMetaRoute
  '/retos': typeof RetosRoute
  '/soporte': typeof SoporteRoute
  '/welcome': typeof WelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/amigos'
    | '/comunidad'
    | '/elige-adiccion'
    | '/enciclopedia'
    | '/login'
    | '/mas'
    | '/nueva-meta'
    | '/retos'
    | '/soporte'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/amigos'
    | '/comunidad'
    | '/elige-adiccion'
    | '/enciclopedia'
    | '/login'
    | '/mas'
    | '/nueva-meta'
    | '/retos'
    | '/soporte'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/amigos'
    | '/comunidad'
    | '/elige-adiccion'
    | '/enciclopedia'
    | '/login'
    | '/mas'
    | '/nueva-meta'
    | '/retos'
    | '/soporte'
    | '/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AmigosRoute: typeof AmigosRoute
  ComunidadRoute: typeof ComunidadRoute
  EligeAdiccionRoute: typeof EligeAdiccionRoute
  EnciclopediaRoute: typeof EnciclopediaRoute
  LoginRoute: typeof LoginRoute
  MasRoute: typeof MasRoute
  NuevaMetaRoute: typeof NuevaMetaRoute
  RetosRoute: typeof RetosRoute
  SoporteRoute: typeof SoporteRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soporte': {
      id: '/soporte'
      path: '/soporte'
      fullPath: '/soporte'
      preLoaderRoute: typeof SoporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retos': {
      id: '/retos'
      path: '/retos'
      fullPath: '/retos'
      preLoaderRoute: typeof RetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-meta': {
      id: '/nueva-meta'
      path: '/nueva-meta'
      fullPath: '/nueva-meta'
      preLoaderRoute: typeof NuevaMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enciclopedia': {
      id: '/enciclopedia'
      path: '/enciclopedia'
      fullPath: '/enciclopedia'
      preLoaderRoute: typeof EnciclopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elige-adiccion': {
      id: '/elige-adiccion'
      path: '/elige-adiccion'
      fullPath: '/elige-adiccion'
      preLoaderRoute: typeof EligeAdiccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidad': {
      id: '/comunidad'
      path: '/comunidad'
      fullPath: '/comunidad'
      preLoaderRoute: typeof ComunidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos': {
      id: '/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AmigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AmigosRoute: AmigosRoute,
  ComunidadRoute: ComunidadRoute,
  EligeAdiccionRoute: EligeAdiccionRoute,
  EnciclopediaRoute: EnciclopediaRoute,
  LoginRoute: LoginRoute,
  MasRoute: MasRoute,
  NuevaMetaRoute: NuevaMetaRoute,
  RetosRoute: RetosRoute,
  SoporteRoute: SoporteRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
