/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NuevaMetaRouteImport } from './routes/nueva-meta'
import { Route as LogrosRouteImport } from './routes/logros'
import { Route as IndexRouteImport } from './routes/index'

const NuevaMetaRoute = NuevaMetaRouteImport.update({
  id: '/nueva-meta',
  path: '/nueva-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const LogrosRoute = LogrosRouteImport.update({
  id: '/logros',
  path: '/logros',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logros': typeof LogrosRoute
  '/nueva-meta': typeof NuevaMetaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logros': typeof LogrosRoute
  '/nueva-meta': typeof NuevaMetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/logros': typeof LogrosRoute
  '/nueva-meta': typeof NuevaMetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/logros' | '/nueva-meta'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/logros' | '/nueva-meta'
  id: '__root__' | '/' | '/logros' | '/nueva-meta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LogrosRoute: typeof LogrosRoute
  NuevaMetaRoute: typeof NuevaMetaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nueva-meta': {
      id: '/nueva-meta'
      path: '/nueva-meta'
      fullPath: '/nueva-meta'
      preLoaderRoute: typeof NuevaMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logros': {
      id: '/logros'
      path: '/logros'
      fullPath: '/logros'
      preLoaderRoute: typeof LogrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LogrosRoute: LogrosRoute,
  NuevaMetaRoute: NuevaMetaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
